[build]
  base = "/"
  publish = "/dist"
  command = "npm install && npm run build"

[dev]
  command = "npm run dev"
  port = 3000

[context.production.environment]
  NODE_VERSION = "18.18.2"
  NPM_VERSION = "9.8.1"

[context.production.node]
  version = "18.18.2"
